Add Android support
aspriddell/csdl pull request #3
Opened 2024-04-26 16:43 UTC by leandroconsiglio

Closes #2 

Published Android native binaries to a new package `csdl.Native.android`

2024-04-26 17:04 UTC, leandroconsiglio commented
Yes, sorry, I realized after creating the PR. Would you prefer that I close this PR and create a new one with a single commit?

2024-04-26 17:05 UTC, aspriddell commented
It doesn't need to be a single commit, but I'm currently looking through the changes and getting an idea what's going on.

I've got a couple of discussion points that I'd like your opinion on so I'd wait until then.

2024-04-26 17:23 UTC, aspriddell requested changes
Looks good for an initial start, a few questions about the triplets/architectures and a pointer on how the packages should be bundled but apart from that it looks good :+1:

I'm not 100% sure on the practicality of producing a dedicated x64 binary but if you specifically need it then there's no harm. Just needs all the commits squashing and apply any changes on top of it then it'll be good to go.

2024-04-26 17:23 UTC, aspriddell commented on .github/workflows/native-build.yml
> +            wget -nv -O android-ndk.zip https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
Taking a look online, `r25c` is an unsupported NDK release. Is there any reason for using this version over [r26d](https://github.com/android/ndk/wiki#supported-downloads)?

As an aside, there's an [action](https://github.com/nttld/setup-ndk) available that can install the NDK and cache it which would be useful for speeding up builds and seems to provide an [output for ANDROID_NDK_HOME](https://github.com/nttld/setup-ndk?tab=readme-ov-file#using-the-installation-path), don't know whether you saw this but might be worth trying out?

2024-04-26 17:23 UTC, aspriddell commented on .github/workflows/native-build.yml
> +      - uses: actions/download-artifact@v4
These will end up in the same package as the desktop runtimes. It would be better if a new job called `package-android` was created but only copies out to the android directories and when building uses the command below to override the package id:
```
dotnet pack -c Release -p:Version=${{ github.event.inputs.version }} -o ./packages -p:PackageId=csdl.Native.Android native/nuget
```

2024-04-26 17:23 UTC, aspriddell commented on .github/workflows/native-build.yml
> +          path: native/nuget/runtimes/android-x86_64/native
I _think_ this name is wrong, and should just be `android-x64`, though as mentioned previously (and in the top comment) is this actually required for any devices?

2024-04-26 17:23 UTC, aspriddell commented on native/build/triplets/release-android-arm.cmake
> +set(VCPKG_BUILD_TYPE release)
These could be put into a `triplet-common-android.cmake` file to keep all the options in the same place so:

- `VCPKG_CMAKE_SYSTEM_NAME`
- `VCPKG_BUILD_TYPE`
- `VCPKG_CRT_LINKAGE`
- `VCPKG_LIBRARY_LINKAGE`

are all set in one place and replace the commented out line with an include for this new file

2024-04-26 17:23 UTC, aspriddell commented on native/build/triplets/release-android-arm.cmake
> +set(VCPKG_MAKE_BUILD_TRIPLET "--host=armv7a-linux-android")
This [community-submitted triplet](https://github.com/microsoft/vcpkg/blob/master/triplets/community/arm-android.cmake) has this down as `armv7a-linux-androideabi` and also sets `-DANDROID_ARM_NEON=OFF` in configure options.

2024-04-26 18:32 UTC, leandroconsiglio commented on native/build/triplets/release-android-arm.cmake
> +set(VCPKG_MAKE_BUILD_TRIPLET "--host=armv7a-linux-android")
I just tried using these values, but it throws an error when building. I really think there is no difference between the two.

2024-04-27 08:30 UTC, aspriddell reviewed
Looks much better, thanks for your work.

I'll test my android build skills on linux and give this a go and try to get it running on an ancient nexus 5x or samsung tablet and let you know how it goes.

2024-04-27 12:06 UTC, aspriddell commented on native/build/triplets/release-android-arm.cmake
> +set(VCPKG_MAKE_BUILD_TRIPLET "--host=armv7a-linux-android")
I found that using either made no real difference, so I guess it's fine to leave as-is

2024-04-27 12:07 UTC, aspriddell commented
I've had a go at building the libraries using the NDK r26d and all seems to work, though I had to set `ANDROID_NDK` and `ANDROID_NDK_HOME` to get it to work properly.

I'll have a go at actually testing the devices tomorrow sometime as I need to find a device that works though if you want the packages and don't want to wait you can change the github packages url to use `${{ github.repository_owner }}` instead of `aspriddell` in the nuget urls and manually run a full publish to get packages.

2024-04-28 19:17 UTC, aspriddell commented
I've had a go at taking the built binaries from [your last successful build run](https://github.com/leandroconsiglio/csdl/actions/runs/8851440428) but on an old samsung sm-t580 tablet running `using var torrentClient = new TorrentClient()` would fail (the pointer returned would be negative) and trying to load a torrent file in by passing in raw bytes would completely crash the app and produce little debugging information to go off.

How did you test these libraries worked on a device and did you test the native files alone or with the C# library? It might be that one device is the culprit and to eliminate that I'll test it on a Nexus 5X tomorrow.

2024-04-30 20:38 UTC, leandroconsiglio commented
Sorry, I've had a busy few days. 
I have created a proof of concept in the following branch with an Android project. [https://github.com/leandroconsiglio/csdl/tree/android_poc](url) 
One important thing, I had to comment out the packagerefence to csdl.native in the csdl project because it conflicted with the Android project's lib folder. But when the binaries are in the new nuget package that problem should not occur I think.

2024-04-30 20:53 UTC, aspriddell commented
Thanks for that, I've taken a quick look and will have a go at embedding a torrent file in the program and attempt to parse it within the app. It's most likely the device I'm using has some strange configuration (I've had issues with MAUI Blazor projects before with it) so will use the 5X as mentioned above.

One other thing that will need to be sorted with the android nuget project is how the libs are copied. It'll need to go in a format the same as the fork you linked with `AndroidNativeLibrary` but don't worry about that (I'll do it once everything else is sorted)

2024-04-30 21:08 UTC, aspriddell commented
> You can also use an emulator

I want to use physical devices because emulating an x86_64 device and then deploying to find it doesn't work on any "real" device isn't something I want to deal with. I only have access to those two devices (and potentially a samsung phone).

The main reason I'm not going all in and fixing issues later is when support is added (via merging this) there will be an additional maintenance burden on a platform that I can't easily test, hence I want everything rock solid beforehand.

2024-05-01 22:42 UTC, leandroconsiglio commented
I have a question that I wanted to ask you, but it has nothing to do with Android support.
I was reviewing the native code, especially the library.h and library.cpp files. Have you created them with any automated tool? Or you have created them manually? I would like to add other functions that libtorrent provides.

2024-05-02 05:42 UTC, aspriddell commented
It's all written without any automated tooling.

2024-05-02 20:03 UTC, aspriddell commented
I've tested on the Nexus 5X and it works. I've got a quick checklist of tasks that need to happen for merging (though this is for me and I'll finish the rest):

- [ ] Disable x86 builds (they don't work due to struct alignment changes)
- [ ] Add `android` folder to `csdl.Native` with the blank `_._` file (to prevent android builds using linux libs then excluding them)
- [ ] Create a separate `csdl.Native.android` with the libraries copied into `libs/x86_64`, `libs/armeabi-v7a`, `libs/arm64-v8a`
- [ ] Update the documentation to add android as supported (in a limited fashion)

I think the samsung tablet is armeabi-v7a and might be failing due to the pointer being negative (but still valid). I'll also give that another check and alter the managed-side as needed.

2024-05-03 14:32 UTC, aspriddell approved these changes
I've applied my remaining to-dos, if you would be able to check over to ensure nothing has been forgotten I'll get this in and some packages built

2024-05-03 15:11 UTC, leandroconsiglio commented
Everything looks fine!

2024-05-03 15:27 UTC, merged

2024-05-08 15:07 UTC, aspriddell commented
(packages are now available via GitHub NuGet and actual NuGet)